[build]
  command = "npm run build"
  publish = "dist/phonebook-app/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[plugins]
  disabled = "@netlify/angular-runtime"